#!/bin/bash

# Checking if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

# Checking if the specified Python file exists
if [ ! -f "$PYFILE" ]; then
    echo "Error: Python file '$PYFILE' not found."
    exit 1
fi

# Running the Python script
/usr/bin/python3 "$PYFILE"
